@host=https://api.elevenlabs.io/v1
@voice_id=21m00Tcm4TlvDq8ikWAM

# https://elevenlabs.io/docs/voices/premade-voices#languages
# https://help.elevenlabs.io/hc/en-us/articles/21811236079505-How-do-I-find-the-model-ID

#####

GET /voices
xi_api_key: sk_f750d17592caac9551f6736bab0027d58c49a1d1b4e96000


#####

POST /text-to-speech/{{voice_id}}/with-timestamps
xi_api_key: sk_f750d17592caac9551f6736bab0027d58c49a1d1b4e96000
Content-Type: application/json

{
  "text": "Elevenlabs へ ようこそ ！ \n以下 の 再生 ボタン を クリック し て 、 この テキスト を 日本語 の 音声 に 変換 し て ください 。\n ドロップダウンメニュー を 使用 し て 、 自分 の テキスト を 追加 し たり 、 声 を カスタマイズ し たり でき ます 。",
  "model_id": "eleven_multilingual_v2",
  "voice_settings": {
    "stability": 0.5,
    "similarity_boost": 0.75
  }
}

>>! ./outputRedirection_jp.json

#####

POST /text-to-speech/{{voice_id}}/with-timestamps
xi_api_key: sk_f750d17592caac9551f6736bab0027d58c49a1d1b4e96000
Content-Type: application/json

{
  "text": "Born and raised in the charming south, \n I can add a touch of sweet southern hospitality \n to your audiobooks and podcasts \n",
  "model_id": "eleven_multilingual_v2",
  "voice_settings": {
    "stability": 0.5,
    "similarity_boost": 0.75
  }
}

>>! ./outputRedirection_en.json