# https://httpyac.github.io/guide/request.html#request-line

@host=http://localhost:9090

###
POST /Animation.FrameAnimation
Content-Type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST /Animation.FrameAnimation

name=sample
time=Wed, 21 Oct 2015 18:27:50 GMT


###
/Animation.HorseAnimation

###
/Animation.SpriteTiles

###
/Animation.TimeAnimation

###
"Animation.Transitions

###
/GettingStarted.Clock

###
/GettingStarted.HelloWorld

###
/GettingStarted.HelloWorldLocalized

###
/GettingStarted.Timer

###
/Graphics.AnchorPoints

###
/Graphics.CompositeViewer

###
/Graphics.Container

###
/Graphics.EmitterBasic

###
/Graphics.EmitterPhysics

###
/Graphics.EmitterViewer

###
/Graphics.FilterGraph

###
/Graphics.FilterViewer

###
/Graphics.Fishies

###
/Graphics.Flashlight

###
/Graphics.GeneratorViewer

###
/Graphics.PatternFill

###
/Graphics.Perspective

###
/Graphics.PolyLines

###
/Graphics.SnapshotEraser

###
/Graphics.SnapshotPaint

###
/Graphics.TextureLoad

###
/Graphics.VectorShapes



###
/Hardware.Accelerometer

###
/Hardware.Compass

###
/Hardware.DeviceInfo

###
/Hardware.DynamicImageResolution

###
/Hardware.GPS

###
/Hardware.Gyroscope

###
/Hardware.InputDevices

###
/Hardware.KeyEvents

###
/Hardware.SystemEvents

###
/Interface.ButtonEvents

###
/Interface.Composer -- error

###
/Interface.DesktopWindow

###
/Interface.DragMe

###
/Interface.NativeDisplayObjects

###
/Interface.NativeKeyboard

###
/Interface.Orientation

###
/Interface.PinchZoomGesture

###
/Interface.SlideView

###
/Interface.StatusBar

###
/Interface.WidgetDemo --error


###
/Media.AudioPlayer

###
/Media.Camera

###
/Media.NewVideo

###
/Media.PhotoPicker

###
/Media.SimpleAudioRecorder -- not playing

###
/Media.VideoPlayer


###
/Monetization.InAppPurchase

###
/Monetization.Licensing

###
/Networking.AsynchHTTP

###
/Networking.AsynchImageDownload -- error

###
/Networking.ComposeEmailSMS

###
/Networking.Facebook -- plugin, add the plugin to build.settings

###
/Networking.Twitter

###
/Physics.Bridge

###
/Physics.Bullet

###
/Physics.Chains

###
/Physics.CollisionDetection

###
/Physics.CollisionFilters

###
/Physics.HelloPhysics

###
/Physics.Joints

###
/Physics.LiquidFun-ColorFaucet

###
/Physics.LiquidFun-ColorGroup -- crash

###
/Physics.LiquidFun-Transparency

###
/Physics.MultiPuck

###
/Physics.PhysicsContact

###
/Physics.RagDoll

###
/Physics.RayCasting

###
/Physics.RegionQuery

###
/Physics.ShapeTumbler

###
/Physics.SimplePool -- use config.lua with 768x1024

###
/Storage.AppPreferences

###
/Storage.FileDemo

###
/Storage.SaveTable

###
/Storage.ScreenCaptureToFile

###
/Storage.SQLite

###
/System.GooglePushNotifications

###
/System.LocalNotifications -- plugin error, add the plugin to build.settings
