name: "Deploy Kwik Solar2D base-proj"

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy-to-kwik5-project-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Clone Repository kwik5-project-template
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'develop'
          owner: 'kwiksher'
          repository: 'kwik5-project-template'

      - name: copy psd lua files to UXP/kwik-exporter/kwik/base-proj/Solar2D and Photoshop
        run: |
          cd UXP
          source ./copy_solar2d.command
          source ./copy_photoshop.command
      - name: copy solar2d and photoshop folders to kwik5-project-template
        run: |
          cp -rf UXP/kwik-exporter/kwik/base-proj/Photoshop kwik5-project-template
          cp -rf UXP/kwik-exporter/kwik/base-proj/Solar2D kwik5-project-template
          rm -rf kwik5-project-template/Solar2D/plugin
          cd kwik5-project-template
          git config --global user.email "yamamoto@kwiksher.com"
          git config --global user.name "kwiksher"
          git add -f Solar2D/*
          git add -f Photoshop/*
          git add -f UXP/*
          git commit -m "Update kwik exporter kwik/base-proj"

          #cp -rf UXP/kwik-exporter/kwik kwik5-project-template/UXP/kwik-exporter

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: develop
          directory: kwik5-project-template
          repository: kwiksher/kwik5-project-template
